//! TCG opcode enumeration mirror.
//!
//! Numbers MUST stay in sync with `include/tcg/tcg-opc.h`. The enum is
//! generated by:
//!
//! ```text
//! typedef enum TCGOpcode {
//! #define DEF(name, oargs, iargs, cargs, flags) INDEX_op_ ## name,
//! #include "tcg/tcg-opc.h"
//! #undef DEF
//!     NB_OPS,
//! } TCGOpcode;
//! ```
//!
//! The numbering is positional inside tcg-opc.h — every reordering of
//! the header must be reflected here. A build-time guard (the
//! `__BUILD_BUG_ON_TCG_OPC_DRIFT` C side check) catches drift.
//!
//! Only opcodes the translator actually consumes are listed by name.
//! Anything else flows through [`Op::Other(u16)`].

#![allow(non_camel_case_types, dead_code)]

/// Symbolic mirror of `enum TCGOpcode`. The integer value MUST match
/// the position in tcg-opc.h. Keep this list in the same order as the
/// header so the constants can be cross-checked visually.
#[repr(u16)]
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum Opc {
    // predefined ops
    Discard      = 0,
    SetLabel     = 1,
    // variable parameters
    Call         = 2,
    Br           = 3,
    Brcond       = 4,
    Mb           = 5,
    Mov          = 6,
    // integer arithmetic / logic - same order as tcg-opc.h
    Add          = 7,
    And          = 8,
    Andc         = 9,
    Bswap16      = 10,
    Bswap32      = 11,
    Bswap64      = 12,
    Clz          = 13,
    Ctpop        = 14,
    Ctz          = 15,
    Deposit      = 16,
    Divs         = 17,
    Divs2        = 18,
    Divu         = 19,
    Divu2        = 20,
    Eqv          = 21,
    Extract      = 22,
    Extract2     = 23,
    Ld8u         = 24,
    Ld8s         = 25,
    Ld16u        = 26,
    Ld16s        = 27,
    Ld32u        = 28,
    Ld32s        = 29,
    Ld           = 30,
    Movcond      = 31,
    Mul          = 32,
    Muls2        = 33,
    Mulsh        = 34,
    Mulu2        = 35,
    Muluh        = 36,
    Nand         = 37,
    Neg          = 38,
    Negsetcond   = 39,
    Nor          = 40,
    Not          = 41,
    Or           = 42,
    Orc          = 43,
    Rems         = 44,
    Remu         = 45,
    Rotl         = 46,
    Rotr         = 47,
    Sar          = 48,
    Setcond      = 49,
    Sextract     = 50,
    Shl          = 51,
    Shr          = 52,
    St8          = 53,
    St16         = 54,
    St32         = 55,
    St           = 56,
    Sub          = 57,
    Xor          = 58,
    // carry ops
    Addco        = 59,
    Addc1o       = 60,
    Addci        = 61,
    Addcio       = 62,
    Subbo        = 63,
    Subb1o       = 64,
    Subbi        = 65,
    Subbio       = 66,
    // 32-bit-specific
    Brcond2I32   = 67,
    Setcond2I32  = 68,
    // size-changing
    ExtI32I64    = 69,
    ExtuI32I64   = 70,
    ExtrlI64I32  = 71,
    ExtrhI64I32  = 72,
    InsnStart    = 73,
    ExitTb       = 74,
    GotoTb       = 75,
    GotoPtr      = 76,
    PluginCb     = 77,
    PluginMemCb  = 78,
    QemuLd       = 79,
    QemuSt       = 80,
    QemuLd2      = 81,
    QemuSt2      = 82,
    // floating-point block starts here; we look these up by name
    // (see `Op::from_raw`) since the FP and vector sections are large
    // and only partially handled.
}

/// Symbolic abstraction over the raw opcode integer. The translator
/// matches on this rather than the bare `u16` so future additions /
/// reorderings of tcg-opc.h surface as compile errors here.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Op {
    Known(Opc),
    /// Anything not in `Opc` - the translator's fallback path returns
    /// [`CRANELIFT_TCG_ERR_UNSUPPORTED_OP`] for these.
    Other(u16),
}

impl Op {
    pub fn from_raw(raw: u16) -> Self {
        // Cover the named region with a fast table; anything past
        // the highest-known opcode is `Other`.
        if raw <= Opc::QemuSt2 as u16 {
            // SAFETY: opcodes 0..=82 are all named above; the enum
            // is `#[repr(u16)]` so the value is a valid discriminant.
            Op::Known(unsafe { core::mem::transmute::<u16, Opc>(raw) })
        } else {
            Op::Other(raw)
        }
    }

    pub fn raw(self) -> u16 {
        match self {
            Op::Known(o) => o as u16,
            Op::Other(r) => r,
        }
    }
}

/// Type tag mirroring TCGType. Only the cases the translator cares
/// about are named.
#[repr(u8)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum TcgType {
    I32  = 0,
    I64  = 1,
    I128 = 2,
    V64  = 3,
    V128 = 4,
    V256 = 5,
}

impl TcgType {
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            1 => TcgType::I64,
            2 => TcgType::I128,
            3 => TcgType::V64,
            4 => TcgType::V128,
            5 => TcgType::V256,
            _ => TcgType::I32,
        }
    }
}

/// Mirror of `enum TCGCond` in include/tcg/tcg-cond.h. Values are
/// bit-encoded: bit 0 = invert, bit 1 = swap-needs-2, bit 2 = swap,
/// bit 3 = unsigned.
#[repr(u8)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum TcgCond {
    Never  = 0,
    Always = 1,
    Eq     = 8,
    Ne     = 9,
    /// `(a & b) == 0`
    TstEq  = 12,
    /// `(a & b) != 0`
    TstNe  = 13,
    Lt     = 2,
    Ge     = 3,
    Gt     = 6,
    Le     = 7,
    Ltu    = 10,
    Geu    = 11,
    Gtu    = 14,
    Leu    = 15,
}

impl TcgCond {
    pub fn from_raw(raw: u64) -> Option<Self> {
        Some(match raw as u8 {
            0  => TcgCond::Never,
            1  => TcgCond::Always,
            8  => TcgCond::Eq,
            9  => TcgCond::Ne,
            12 => TcgCond::TstEq,
            13 => TcgCond::TstNe,
            2  => TcgCond::Lt,
            3  => TcgCond::Ge,
            6  => TcgCond::Gt,
            7  => TcgCond::Le,
            10 => TcgCond::Ltu,
            11 => TcgCond::Geu,
            14 => TcgCond::Gtu,
            15 => TcgCond::Leu,
            _  => return None,
        })
    }
}

/// Mirror of the flags in `TCGOpDef::flags`. Values are authoritative
/// in `include/tcg/tcg.h` -- do NOT guess or shuffle this list.
pub mod flags {
    pub const TCG_OPF_BB_EXIT: u16       = 0x0001;
    pub const TCG_OPF_BB_END: u16        = 0x0002;
    pub const TCG_OPF_CALL_CLOBBER: u16  = 0x0004;
    pub const TCG_OPF_SIDE_EFFECTS: u16  = 0x0008;
    pub const TCG_OPF_INT: u16           = 0x0010;
    pub const TCG_OPF_NOT_PRESENT: u16   = 0x0020;
    pub const TCG_OPF_VECTOR: u16        = 0x0040;
    pub const TCG_OPF_COND_BRANCH: u16   = 0x0080;
    pub const TCG_OPF_CARRY_OUT: u16     = 0x0100;
    pub const TCG_OPF_CARRY_IN: u16      = 0x0200;
    pub const TCG_OPF_FP: u16            = 0x0400;
}
